# Generated by Django 3.1.4 on 2021-04-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysevr', '0002_auto_20210404_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcecode',
            name='files',
            field=models.FileField(upload_to=''),
        ),
    ]
