# Generated by Django 3.1.4 on 2021-04-04 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sysevr', '0003_auto_20210404_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcecode',
            name='files',
        ),
    ]
