# Generated by Django 3.1.4 on 2021-04-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysevr', '0008_auto_20210404_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcecode',
            name='files',
            field=models.TextField(),
        ),
    ]
